name: aur-autobump

on:
  schedule: [cron: "12 1 * * *"]
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    container: archlinux:latest
    strategy:
      matrix:
        pkg: [fdbcli-bin, fdbbackup-bin, fdbserver-bin, fdbmonitor-bin]
    steps:
      - run: pacman -Sy --noconfirm --needed git jq nvchecker devtools

      - env:
          KEY: ${{ secrets.AUR_SSH_KEY }}
        run: |
          install -dm 755 ~/.ssh
          cat > ~/.ssh/aur <<< "$KEY"
          chmod 600 ~/.ssh/aur
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          cat >> ~/.ssh/config <<'EOF'
          Host aur.archlinux.org
            User aur
            IdentityFile ~/.ssh/aur
            IdentitiesOnly yes
          EOF

      - run: git clone "ssh://aur@aur.archlinux.org/${{ matrix.pkg }}.git" aur

      - id: v
        run: |
          cd aur
          pkgctl version check --json > v.json
          echo "need=$(jq -r '.[0].out_of_date' v.json)" >> $GITHUB_OUTPUT
          echo "new=$(jq -r '.[0].upstream_version' v.json)" >> $GITHUB_OUTPUT

      - if: steps.v.outputs.need == 'true'
        env:
          GIT_AUTHOR_NAME: ${{ secrets.AUR_USERNAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.AUR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.AUR_USERNAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.AUR_EMAIL }}
        run: |
          cd aur
          pkgctl version upgrade
          makepkg --printsrcinfo > .SRCINFO
          git add PKGBUILD .SRCINFO
          git commit -m "auto: bump to ${{ steps.v.outputs.new }}"
          git push origin HEAD:master
